// ==UserScript==
// @name         Hide Navigation Bars
// @match        https://*.x.com/*
// @match        https://*.youtube.com/*
// @match        https://*.reddit.com/*
// @match        https://*.redlib.catsarch.com/*
// @grant        none
// ==/UserScript==
const EXCLUDED_SITES = [
    "https://*.youtube.com/watch*",
    "https://*.youtube.com/shorts/*"
];
(()=>{let h=false,t=0,p=0,M=new Set,d=true,U=s=>new RegExp("^"+s.replace(/[.+?^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(location.href),K=()=>!EXCLUDED_SITES.some(U),T=()=>((window.visualViewport?.height)||innerHeight)*.05,s=document.createElement("style");s.textContent="html.AHN-hide .AHN{display:none!important}";document.documentElement.append(s);let V=e=>e?.matches?.("video,audio,iframe")||e?.querySelector?.("video,audio,iframe"),o=new MutationObserver(m=>{if(!d){h&&S(0);return}if(!h)return;let r=0;for(let x of m)if(x.type==="attributes"){M.has(x.target)&&!x.target.classList.contains("AHN")&&x.target.classList.add("AHN")}else if(!M.has(x.target)&&[...x.addedNodes,...x.removedNodes].some(n=>n.nodeType===1))r=1;r&&!p&&(p=1,requestAnimationFrame(()=>{p=0,d&&h&&E()}))}),A=e=>{if(!e||M.has(e)||V(e))return;M.add(e);e.classList.add("AHN");o.observe(e,{attributes:true,attributeFilter:["class"]})},E=()=>{if(!d)return;let Q=new Map,W=innerWidth,H=innerHeight,L=Math.min(300,H*.4),cs=new Map,rs=new Map,vs=new Map,F=n=>{if(!cs.has(n))cs.set(n,getComputedStyle(n).position);return cs.get(n)},B=n=>{if(!rs.has(n))rs.set(n,n.getBoundingClientRect());return rs.get(n)},J=n=>{if(!vs.has(n))vs.set(n,!!V(n));return vs.get(n)};for(let b of[0,1])for(let Y of(b?[H-120,H-80,H-40,H-2]:[2,40,80,120]))for(let X of[W*.06,W*.25,W*.5,W*.75,W*.94])for(let e of document.elementsFromPoint(X,Y)){let P=[],f=-1;for(let n=e;n&&n!==document.body&&n!==document.documentElement;n=n.parentElement){P.push(n);if(f<0){let c=F(n);if(c==="fixed"||c==="sticky")f=P.length-1}}if(f<0)continue;let q=null;for(let i=0;i<=f;i++){let n=P[i],r=B(n);if(r.width>W*.45&&r.height>18&&r.height<L&&(b?r.bottom>H-130:r.top<130)&&!J(n))q=n}if(q){for(let n=q.parentElement;n&&n!==document.body;n=n.parentElement){let r=B(n);if(r.width>W*.45&&r.height<L&&(b?r.bottom>H-130:r.top<130)&&!J(n))q=n;else break}Q.set(q,b)}}for(let[e,b]of[...Q])for(let[p,c]of Q)if(e!==p&&p.contains(e)&&b===c){Q.delete(e);break}for(let e of Q.keys())A(e)},S=v=>{h=v;if(v&&d){M.clear();document.querySelectorAll(".AHN").forEach(e=>e.classList.remove("AHN"));E();document.documentElement.classList.add("AHN-hide");o.observe(document.documentElement,{subtree:true,childList:true})}else{o.disconnect();document.documentElement.classList.remove("AHN-hide");M.forEach(e=>e.classList.remove("AHN"));M.clear()}},R=()=>{t=0;if(!d){h&&S(0);return}let q=Math.max(0,scrollY)>T();q!==h&&S(q)},Z=()=>{let n=K();if(n===d)return;d=n,d?R():S(0)};addEventListener("scroll",()=>{d&&!t&&(t=requestAnimationFrame(R))},{passive:true});for(let e of["popstate","hashchange","pageshow"])addEventListener(e,()=>queueMicrotask(Z));document.addEventListener("yt-navigate-finish",Z,true);for(let e of["pushState","replaceState"]){let n=history[e];history[e]=function(){let r=n.apply(this,arguments);return queueMicrotask(Z),r}}Z();R()})();